# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  type        :string           not null
#  object_type :string           not null
#  object_id   :integer          not null
#  date        :datetime
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/events", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Event. As you add validations to Event, be sure to
  # adjust the attributes here as well.
  let(:event) {create :event}

  let(:valid_attributes) {
    {
      type: event.type,
      object_id: event.object_id,
      object_type: event.object_type,
      date: event.date,
      content: event.content,
    }
  }

  let(:invalid_attributes) {
    {type: ''}
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # EventsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      event
      event
      get events_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      event
      get event_url(event), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Event" do
        event
        expect {
          post events_url,
               params: { event: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Event, :count).by(1)
      end

      it "renders a JSON response with the new event" do
        post events_url,
             params: { event: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Event" do
        expect {
          post events_url,
               params: { event: invalid_attributes }, as: :json
        }.to change(Event, :count).by(0)
      end

      it "renders a JSON response with errors for the new event" do
        post events_url,
             params: { event: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {content: 'New content'}
      }

      it "updates the requested event" do
        event
        patch event_url(event),
              params: { event: new_attributes }, headers: valid_headers, as: :json
        event.reload
        expect(event.content).to eq 'New content'
      end

      it "renders a JSON response with the event" do
        event
        patch event_url(event),
              params: { event: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the event" do
        event
        patch event_url(event),
              params: { event: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested event" do
      event
      expect {
        delete event_url(event), headers: valid_headers, as: :json
      }.to change(event.class, :count).by(-1)
    end
  end
end
